# Generated by Django 5.2.6 on 2025-09-19 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('', 'Нет'), ('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('4А', '4А'), ('5А', '5А')], max_length=10, null=True)),
                ('summer', models.CharField(blank=True, choices=[('', 'Нет'), ('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('4А', '4А'), ('5А', '5А')], max_length=10, null=True)),
                ('autumn', models.CharField(blank=True, choices=[('', 'Нет'), ('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('4А', '4А'), ('5А', '5А')], max_length=10, null=True)),
                ('spring', models.CharField(blank=True, choices=[('', 'Нет'), ('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('4А', '4А'), ('5А', '5А')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otc', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True)),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В модерации'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.coordinates')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.user')),
            ],
            options={
                'db_table': 'passes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passes.pass')),
            ],
        ),
    ]
